version: "3"
services:
    frontend:
        build: 
            context: .
        image: frontend
        ports: 
            - "80:80"

networks:
    default:
       external:
          name: allnetwork